apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-productos
  template:
    metadata:
      labels:
        app: micro-productos
    spec:
      containers:
        - name: micro-productos
          image: jhaucatoma/microservicio-aks:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/Productos"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123PP45"