apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-productos
  template:
    metadata:
      labels:
        app: micro-productos
    spec:
      containers:
        - name: micro-productos
          image: grupo4jose.azurecr.io/micro-productos:latest
          ports:
            - containerPort: 8080
    env:
      - name: SPRING_DATASOURCE_URL
        valueFrom:
          secretKeyRef:
            name: micro-productos-db
            key: SPRING_DATASOURCE_URL
      - name: SPRING_DATASOURCE_USERNAME
        valueFrom:
          secretKeyRef:
            name: micro-productos-db
            key: SPRING_DATASOURCE_USERNAME
      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: micro-productos-db
            key: SPRING_DATASOURCE_PASSWORD